// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "TodoList/internal/core/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStatisticsRepository is a mock of StatisticsRepository interface.
type MockStatisticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticsRepositoryMockRecorder
}

// MockStatisticsRepositoryMockRecorder is the mock recorder for MockStatisticsRepository.
type MockStatisticsRepositoryMockRecorder struct {
	mock *MockStatisticsRepository
}

// NewMockStatisticsRepository creates a new mock instance.
func NewMockStatisticsRepository(ctrl *gomock.Controller) *MockStatisticsRepository {
	mock := &MockStatisticsRepository{ctrl: ctrl}
	mock.recorder = &MockStatisticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticsRepository) EXPECT() *MockStatisticsRepositoryMockRecorder {
	return m.recorder
}

// GetTasks mocks base method.
func (m *MockStatisticsRepository) GetTasks(ctx context.Context, userId *int, from, to *time.Time) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, userId, from, to)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockStatisticsRepositoryMockRecorder) GetTasks(ctx, userId, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockStatisticsRepository)(nil).GetTasks), ctx, userId, from, to)
}
